//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using Contracts;
using Contracts.Parameters;
using Contracts.Templates;

namespace LostInSpace
{
	public class EnabledGrandTourContract : GrandTour
	{
		public override bool MeetRequirements ()
		{
			return GetBodies_Reached(false, false).Count > 1;
		}
	}
}

