//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using UnityEngine;

using Contracts;
using Contracts.Parameters;
using Contracts.Templates;

namespace LostInSpace
{
	public class LostInSpaceContract : RescueKerbal
	{
		protected override bool Generate ()
		{
			List<CelestialBody> bodies = Contract.GetBodies_Reached (false, false);

			if (bodies.Count == 0)
			{
				return false;
			}

			this.targetBody = bodies [UnityEngine.Random.Range (0, bodies.Count)];
			if (this.targetBody == null)
			{
				this.targetBody = PSystemManager.Instance.localBodies [1];
			}

			ProtoCrewMember newCrew = HighLogic.CurrentGame.CrewRoster.GetNewKerbal (ProtoCrewMember.KerbalType.Unowned);
			typeof(RescueKerbal)
				.GetField("crewMember", BindingFlags.Instance | BindingFlags.NonPublic)
					.SetValue(this, newCrew);

			newCrew.rosterStatus = ProtoCrewMember.RosterStatus.Assigned;
			newCrew.seat = null;
			newCrew.seatIdx = -1;

			BoardAnyVessel boardAnyVessel = (BoardAnyVessel)this.AddParameter (
				new BoardAnyVessel("Have " + newCrew.name + " board a vessel", BoardAnyVessel.CompleteCondition.All, BoardAnyVessel.CompleteCondition.Any));
			boardAnyVessel.SetFunds (5000f, this.targetBody);
			boardAnyVessel.SetReputation (10f, this.targetBody);
			this.AddParameter (new RecoverKerbal ("Recover " + newCrew.name, RecoverKerbal.CompleteCondition.All, RecoverKerbal.CompleteCondition.All));
			base.SetExpiry ();
			base.SetDeadlineYears (5f, this.targetBody);
			base.SetFunds (10000f, 40000f, this.targetBody);
			base.SetReputation (20f, 20f, this.targetBody);
			return true;
		}
	}
}

